# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from img import about_icons_rc

class Ui_AboutWin(object):
    def setupUi(self, AboutWin):
        AboutWin.setObjectName("AboutWin")
        AboutWin.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AboutWin.sizePolicy().hasHeightForWidth())
        AboutWin.setSizePolicy(sizePolicy)
        AboutWin.setMinimumSize(QtCore.QSize(0, 0))
        AboutWin.setStyleSheet("background-color: rgb(197, 220, 227);")
        self.centralwidget = QtWidgets.QWidget(AboutWin)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.about_VL1 = QtWidgets.QVBoxLayout()
        self.about_VL1.setSpacing(0)
        self.about_VL1.setObjectName("about_VL1")
        self.about_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.about_frame.sizePolicy().hasHeightForWidth())
        self.about_frame.setSizePolicy(sizePolicy)
        self.about_frame.setStyleSheet("\n"
"background-color: rgb(0, 0, 0);")
        self.about_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.about_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.about_frame.setObjectName("about_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.about_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.back_btn = QtWidgets.QPushButton(self.about_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_btn.sizePolicy().hasHeightForWidth())
        self.back_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.back_btn.setFont(font)
        self.back_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back_btn.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    font: 9pt \"Arial\";\n"
"    color: rgb(255, 255, 255);}\n"
"QPushButton:hover{ \n"
"    color: rgb(197, 220, 227);\n"
"}\n"
"QPushButton:pressed{ \n"
"    color: rgb(197, 220, 227);\n"
"    }\n"
"")
        self.back_btn.setIconSize(QtCore.QSize(100, 50))
        self.back_btn.setDefault(False)
        self.back_btn.setFlat(True)
        self.back_btn.setObjectName("back_btn")
        self.horizontalLayout.addWidget(self.back_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 8)
        self.about_VL1.addWidget(self.about_frame)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 87 36pt \"Arial\";\n"
"\n"
"color: rgb(39, 68, 114);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.about_VL1.addWidget(self.label)
        self.about_HL1 = QtWidgets.QHBoxLayout()
        self.about_HL1.setContentsMargins(30, 10, 30, 10)
        self.about_HL1.setObjectName("about_HL1")
        self.about_frame2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.about_frame2.sizePolicy().hasHeightForWidth())
        self.about_frame2.setSizePolicy(sizePolicy)
        self.about_frame2.setMinimumSize(QtCore.QSize(500, 203))
        self.about_frame2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.about_frame2.setAutoFillBackground(False)
        self.about_frame2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 25px;")
        self.about_frame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.about_frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.about_frame2.setObjectName("about_frame2")
        self.gridLayout = QtWidgets.QGridLayout(self.about_frame2)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 10, 0, 10)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.descLBL = QtWidgets.QLabel(self.about_frame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.descLBL.sizePolicy().hasHeightForWidth())
        self.descLBL.setSizePolicy(sizePolicy)
        self.descLBL.setStyleSheet("font: 12pt \"Arial\";\n"
"margin-left: 20px;\n"
"margin-right:20px;")
        self.descLBL.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.descLBL.setWordWrap(True)
        self.descLBL.setObjectName("descLBL")
        self.gridLayout.addWidget(self.descLBL, 1, 0, 1, 1)
        self.picLBL = QtWidgets.QLabel(self.about_frame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picLBL.sizePolicy().hasHeightForWidth())
        self.picLBL.setSizePolicy(sizePolicy)
        self.picLBL.setMinimumSize(QtCore.QSize(0, 255))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        self.picLBL.setFont(font)
        self.picLBL.setStyleSheet("margin-left:0px;\n"
"image: url(:/img/team.png);\n"
"margin-right:0px;\n"
"margin-top:5px;\n"
"margin-bottom:5px;")
        self.picLBL.setText("")
        self.picLBL.setScaledContents(True)
        self.picLBL.setObjectName("picLBL")
        self.gridLayout.addWidget(self.picLBL, 2, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.about_HL1.addWidget(self.about_frame2)
        self.about_VL1.addLayout(self.about_HL1)
        self.about_VL1.setStretch(1, 1)
        self.about_VL1.setStretch(2, 8)
        self.verticalLayout_2.addLayout(self.about_VL1)
        AboutWin.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AboutWin)
        self.statusbar.setObjectName("statusbar")
        AboutWin.setStatusBar(self.statusbar)

        self.retranslateUi(AboutWin)
        QtCore.QMetaObject.connectSlotsByName(AboutWin)

    def retranslateUi(self, AboutWin):
        _translate = QtCore.QCoreApplication.translate
        AboutWin.setWindowTitle(_translate("AboutWin", "About"))
        self.back_btn.setText(_translate("AboutWin", "<<<BACK"))
        self.label.setText(_translate("AboutWin", "ABOUT"))
        self.descLBL.setText(_translate("AboutWin", "This project is a Gesture Controlled Robotic Arm for Dental Operatory Light Self-Positioning System. It is aimed to adjust its lighting position automatically; which can reduce the constant manual adjustment by dental professionals during procedures. This would help improve the productivity and quality of work of dental doctors."))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AboutWin = QtWidgets.QMainWindow()
    ui = Ui_AboutWin()
    ui.setupUi(AboutWin)
    AboutWin.show()
    sys.exit(app.exec_())
