# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'error.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from img import error_icons_rc

class Ui_ERROR(object):
    def setupUi(self, ERROR):
        ERROR.setObjectName("ERROR")
        ERROR.resize(453, 192)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/error.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ERROR.setWindowIcon(icon)
        ERROR.setStyleSheet("background-color: rgb(227, 227, 227);")
        ERROR.setSizeGripEnabled(False)
        ERROR.setModal(False)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ERROR)
        self.verticalLayout_2.setContentsMargins(-1, 20, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.errorLabel = QtWidgets.QLabel(ERROR)
        self.errorLabel.setStyleSheet("\n"
"color:rgb(255, 0, 0);\n"
"font: 87 20pt \"Arial Black\";")
        self.errorLabel.setScaledContents(True)
        self.errorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.errorLabel.setObjectName("errorLabel")
        self.verticalLayout.addWidget(self.errorLabel)
        self.groupBox = QtWidgets.QGroupBox(ERROR)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.groupBox.setFlat
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(-1, 15, -1, 10)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.leftBTN = QtWidgets.QPushButton(self.groupBox)
        self.leftBTN.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.leftBTN.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.leftBTN.setObjectName("leftBTN")
        self.gridLayout.addWidget(self.leftBTN, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.errorMsg = QtWidgets.QLabel(self.groupBox)
        self.errorMsg.setAlignment(QtCore.Qt.AlignCenter)
        self.errorMsg.setWordWrap(True)
        self.errorMsg.setObjectName("errorMsg")
        self.gridLayout.addWidget(self.errorMsg, 1, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 3, 1, 1)
        self.rightBTN = QtWidgets.QPushButton(self.groupBox)
        self.rightBTN.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rightBTN.setStyleSheet("\n"
"background-color: rgb(39, 68, 114);\n"
"color: rgb(255, 255, 255);")
        self.rightBTN.setObjectName("rightBTN")
        self.gridLayout.addWidget(self.rightBTN, 3, 2, 1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 4)
        self.gridLayout.setRowStretch(2, 1)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem3)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(ERROR)
        QtCore.QMetaObject.connectSlotsByName(ERROR)

    def retranslateUi(self, ERROR):
        _translate = QtCore.QCoreApplication.translate
        ERROR.setWindowTitle(_translate("ERROR", "ERROR"))
        self.errorLabel.setText(_translate("ERROR", "ERROR"))
        self.leftBTN.setText(_translate("ERROR", "Ignore"))
        self.errorMsg.setText(_translate("ERROR", "Sample Error Message. Do you want to restart the system?"))
        self.rightBTN.setText(_translate("ERROR", "Restart"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ERROR = QtWidgets.QDialog()
    ui = Ui_ERROR()
    ui.setupUi(ERROR)
    ERROR.show()
    sys.exit(app.exec_())
