# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'instructions.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Instructions(object):
    def setupUi(self, Instructions):
        Instructions.setObjectName("Instructions")
        Instructions.resize(800, 480)
        Instructions.setStyleSheet("background-color: rgb(197, 220, 227);")
        self.centralwidget = QtWidgets.QWidget(Instructions)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(40, -1, 40, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 75 30pt \"Arial\";\n"
                                 "color: rgb(39, 68, 114);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                 "border-radius: 5px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(20, 10, 20, 2)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.activate_lbl = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.activate_lbl.setFont(font)
        self.activate_lbl.setStyleSheet("font: 87 10pt \"Arial Black\";\n"
                                        "")
        self.activate_lbl.setWordWrap(True)
        self.activate_lbl.setObjectName("activate_lbl")
        self.gridLayout.addWidget(self.activate_lbl, 0, 0, 1, 2)
        self.activate_steps = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.activate_steps.setFont(font)
        self.activate_steps.setStyleSheet("\n"
                                          "font: 10pt \"Arial\";")
        self.activate_steps.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.activate_steps.setWordWrap(True)
        self.activate_steps.setIndent(20)
        self.activate_steps.setObjectName("activate_steps")
        self.gridLayout.addWidget(self.activate_steps, 1, 0, 1, 2)
        self.about_steps = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.about_steps.setFont(font)
        self.about_steps.setStyleSheet("\n"
                                       "font: 10pt \"Arial\";")
        self.about_steps.setWordWrap(True)
        self.about_steps.setIndent(20)
        self.about_steps.setObjectName("about_steps")
        self.gridLayout.addWidget(self.about_steps, 5, 0, 1, 2)
        self.code_lbl = QtWidgets.QLabel(self.frame)
        self.code_lbl.setStyleSheet("font: 87 10pt \"Arial Black\";")
        self.code_lbl.setObjectName("code_lbl")
        self.gridLayout.addWidget(self.code_lbl, 2, 0, 1, 1)
        self.about_lbl = QtWidgets.QLabel(self.frame)
        self.about_lbl.setStyleSheet("font: 87 10pt \"Arial Black\";")
        self.about_lbl.setWordWrap(True)
        self.about_lbl.setObjectName("about_lbl")
        self.gridLayout.addWidget(self.about_lbl, 4, 0, 1, 2)
        self.code_steps = QtWidgets.QLabel(self.frame)
        self.code_steps.setStyleSheet("\n"
                                      "font: 10pt \"Arial\";")
        self.code_steps.setIndent(20)
        self.code_steps.setObjectName("code_steps")
        self.gridLayout.addWidget(self.code_steps, 3, 0, 1, 2)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 5)
        self.gridLayout.setRowStretch(2, 1)
        self.gridLayout.setRowStretch(3, 1)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.continue_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.continue_btn.sizePolicy().hasHeightForWidth())
        self.continue_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        self.continue_btn.setFont(font)
        self.continue_btn.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.continue_btn.setStyleSheet("\n"
                                        "QPushButton{\n"
                                        "    background-color: rgb(39, 68, 114);\n"
                                        "    border-radius: 5px;\n"
                                        "    color: rgb(255, 255, 255);}\n"
                                        "QPushButton:hover{ \n"
                                        "    background-color: rgb(24, 43, 71);\n"
                                        "    color: rgb(255, 255, 255)}\n"
                                        "QPushButton:pressed{ \n"
                                        "    background-color: rgb(24, 43, 71);\n"
                                        "    color: rgb(255, 255, 255)}")
        self.continue_btn.setObjectName("continue_btn")
        self.horizontalLayout.addWidget(self.continue_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 8)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        Instructions.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Instructions)
        self.statusbar.setObjectName("statusbar")
        Instructions.setStatusBar(self.statusbar)

        self.retranslateUi(Instructions)
        QtCore.QMetaObject.connectSlotsByName(Instructions)

    def retranslateUi(self, Instructions):
        _translate = QtCore.QCoreApplication.translate
        Instructions.setWindowTitle(_translate("Instructions", "Instructions"))
        self.label.setText(_translate("Instructions", "INSTRUCTIONS"))
        self.activate_lbl.setText(_translate(
            "Instructions", "PROPER WAY TO HANDLE THE SYSTEM"))
        self.activate_steps.setText(_translate("Instructions", "1) Press the CONTINUE button to enter the Main Menu.\n"
                                               "2) Wait for the camera to open.\n"
                                               "3) If camera is open, present your hand gesture and press the Capture pedal switch \n"
                                               "to capture your hand gesture.\n"
                                               "4) Wait for the robot arm to position itself to the corresponding position of the captured hand gesture.\n"
                                               "5) The arm would automatically position the light on the mouth of patient, then you may turn on \n"
                                               " the light by hovering your hand under the dental light. \n"
                                               "6) To stop the movement of robotic arm, capture gesture Five.\n"
                                               "7) If done, turn off the light by hovering under the dental light and reset the position of  robot arm\n"
                                               " by pressing the Reset pedal switch.\n"
                                               "8) To turn off the system, click the Settings button and select Shutdown button.\n"
                                               ""))
        self.about_steps.setText(_translate("Instructions", "1) Click the About button on the Main Menu\n"
                                            "2) You may now see a short description about the project and a short introduction on the inventors.\n"
                                            ""))
        self.code_lbl.setText(_translate("Instructions", "CHANGE PASSCODE"))
        self.about_lbl.setText(_translate(
            "Instructions", "CHECK  INFORMATION ABOUT THE INVENTORS"))
        self.code_steps.setText(_translate("Instructions", "1) To change the passcode, click the Settings button and select Set Passcode.\n"
                                           "2) Make sure that the input passcode is 4 digits and click the done button.\n"
                                           "3) To remove the passcode, enter a blank input instead.\n"
                                           ""))
        self.continue_btn.setText(_translate("Instructions", "  CONTINUE  "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Instructions = QtWidgets.QMainWindow()
    ui = Ui_Instructions()
    ui.setupUi(Instructions)
    Instructions.show()
    sys.exit(app.exec_())
