# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main4.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from img import main_icons_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 470)
        MainWindow.setStyleSheet("#MainWindow{background-color: rgb(197, 220, 227);}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.VLayout1 = QtWidgets.QVBoxLayout()
        self.VLayout1.setObjectName("VLayout1")
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.VLayout1.addItem(spacerItem)
        self.HLayout1 = QtWidgets.QHBoxLayout()
        self.HLayout1.setObjectName("HLayout1")
        spacerItem1 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HLayout1.addItem(spacerItem1)
        self.VLayout2 = QtWidgets.QVBoxLayout()
        self.VLayout2.setObjectName("VLayout2")
        self.imageLBL = QtWidgets.QLabel(self.centralwidget)
        self.imageLBL.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.imageLBL.setAlignment(QtCore.Qt.AlignCenter)
        self.imageLBL.setObjectName("imageLBL")
        self.VLayout2.addWidget(self.imageLBL)
        self.HLayout1.addLayout(self.VLayout2)
        spacerItem2 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HLayout1.addItem(spacerItem2)
        self.VLayout3 = QtWidgets.QVBoxLayout()
        self.VLayout3.setObjectName("VLayout3")
        self.aboutBTN = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aboutBTN.sizePolicy().hasHeightForWidth())
        self.aboutBTN.setSizePolicy(sizePolicy)
        self.aboutBTN.setMinimumSize(QtCore.QSize(0, 1))
        self.aboutBTN.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.aboutBTN.setAutoFillBackground(False)
        self.aboutBTN.setStyleSheet("QPushButton{\n"
"    color: rgb(255,255,255);\n"
"    image: url(:/img/ABOUT.png);\n"
"    font: 40pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(39, 68, 114);\n"
"    border-radius: 25px;\n"
"    position:bottom;\n"
"}\n"
"QPushButton:hover{ \n"
"    background-color: rgb(24, 43, 71);\n"
"    color: rgb(255, 255, 255)}\n"
"QPushButton:pressed{ \n"
"    background-color: rgb(24, 43, 71);\n"
"    color: rgb(255, 255, 255)}")
        self.aboutBTN.setText("")
        self.aboutBTN.setObjectName("aboutBTN")
        self.VLayout3.addWidget(self.aboutBTN)
        spacerItem3 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.VLayout3.addItem(spacerItem3)
        self.settingsBTN = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsBTN.sizePolicy().hasHeightForWidth())
        self.settingsBTN.setSizePolicy(sizePolicy)
        self.settingsBTN.setMinimumSize(QtCore.QSize(1, 0))
        self.settingsBTN.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settingsBTN.setStyleSheet("QPushButton{\n"
"    color: rgb(255,255,255);\n"
"    image: url(:/img/settings.png);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(39, 68, 114);\n"
"    border-radius: 25px;\n"
"    position:bottom;\n"
"}\n"
"QPushButton:hover{ \n"
"    background-color: rgb(24, 43, 71);\n"
"    color: rgb(255, 255, 255)}\n"
"QPushButton:pressed{ \n"
"    background-color: rgb(24, 43, 71);\n"
"    color: rgb(255, 255, 255)}")
        self.settingsBTN.setText("")
        self.settingsBTN.setObjectName("settingsBTN")
        self.VLayout3.addWidget(self.settingsBTN)
        self.VLayout3.setStretch(0, 1)
        self.VLayout3.setStretch(2, 1)
        self.HLayout1.addLayout(self.VLayout3)
        spacerItem4 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HLayout1.addItem(spacerItem4)
        self.HLayout1.setStretch(1, 5)
        self.HLayout1.setStretch(3, 1)
        self.VLayout1.addLayout(self.HLayout1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.VLayout1.addItem(spacerItem5)
        self.VLayout1.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.VLayout1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.imageLBL.setText(_translate("MainWindow", "Please Wait for the Camera "))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
