# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'passcode.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDesktopWidget
from img import passcode_icons_rc


class Ui_Passcode(object):
    def setupUi(self, Passcode):
        Passcode.setObjectName("Passcode")
        Passcode.resize(800, 480)
        Passcode.setStyleSheet("\n"
                               "QWidget{\n"
                               "    \n"
                               "    background-color: rgb(255, 255, 255);\n"
                               "}\n"
                               "QPushButton{\n"
                               "border: none;\n"
                               "border-radius:25px;\n"
                               "background-color: rgb(212, 211, 197);\n"
                               "color: rgb(25, 25, 25);\n"
                               "\n"
                               "font: 20pt \"Arial\";\n"
                               "\n"
                               "\n"
                               "}\n"
                               "\n"
                               "\n"
                               "\n"
                               "QPushButton:pressed{ \n"
                               "    border-radius:15px;\n"
                               "    background-color: rgb(197, 220, 227);\n"
                               "    color: rgb(25, 25, 25);}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Passcode)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, 10, 5, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.go_back_btn = QtWidgets.QPushButton(Passcode)
        self.go_back_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.go_back_btn.setStyleSheet("QPushButton{\n"
                                       "background-color: rgb(255, 255, 255);\n"
                                       "font: 10pt \"Arial\";\n"
                                       "text-align:left;"
                                       "}\n"
                                       "\n"
                                       "\n"
                                       "QPushButton:pressed{ \n"
                                       "    \n"
                                       "    color: rgb(24, 43, 71);\n"
                                       "\n"
                                       "text-align:left;"
                                       "}")
        self.go_back_btn.setFlat(True)
        self.go_back_btn.setObjectName("go_back_btn")
        self.verticalLayout.addWidget(self.go_back_btn)
        self.title_lbl = QtWidgets.QLabel(Passcode)
        self.title_lbl.setStyleSheet("font: 87 20pt \"Arial Black\";\n"
                                     "\n"
                                     "color: rgb(39, 68, 114);")
        self.title_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.title_lbl.setObjectName("title_lbl")
        self.verticalLayout.addWidget(self.title_lbl)
        self.passcode_lbl = QtWidgets.QLabel(Passcode)
        self.passcode_lbl.setStyleSheet("font: 35pt \"Arial\";\n"
                                        "background-color: rgb(212, 211, 197);\n"
                                        " border-radius: 15px;\n"
                                        " margin-left:50px;\n"
                                        "margin-right:50px;")
        self.passcode_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.passcode_lbl.setObjectName("passcode_lbl")
        self.verticalLayout.addWidget(self.passcode_lbl)
        self.notif_lbl = QtWidgets.QLabel(Passcode)
        self.notif_lbl.setStyleSheet("font: 12pt \"Arial\";")
        self.notif_lbl.setText("")
        self.notif_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.notif_lbl.setObjectName("notif_lbl")
        self.verticalLayout.addWidget(self.notif_lbl)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(35, -1, 35, -1)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_3 = QtWidgets.QPushButton(Passcode)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 65))
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(Passcode)
        self.pushButton_9.setMinimumSize(QtCore.QSize(0, 65))
        self.pushButton_9.setStyleSheet("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 2, 2, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(Passcode)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 65))
        self.pushButton_5.setStyleSheet("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(Passcode)
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 65))
        self.pushButton_7.setStyleSheet("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 2, 0, 1, 1)
        self.pushButton_0 = QtWidgets.QPushButton(Passcode)
        self.pushButton_0.setMinimumSize(QtCore.QSize(0, 65))
        self.pushButton_0.setStyleSheet("")
        self.pushButton_0.setObjectName("pushButton_0")
        self.gridLayout.addWidget(self.pushButton_0, 3, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(Passcode)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 65))
        self.pushButton_6.setStyleSheet("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 2, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(Passcode)
        self.pushButton_8.setMinimumSize(QtCore.QSize(0, 65))
        self.pushButton_8.setStyleSheet("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 2, 1, 1, 1)
        self.back_btn = QtWidgets.QPushButton(Passcode)
        self.back_btn.setMinimumSize(QtCore.QSize(0, 65))
        self.back_btn.setStyleSheet("\n"
                                    "image: url(:/img/backspace.png);")
        self.back_btn.setText("")
        self.back_btn.setObjectName("back_btn")
        self.gridLayout.addWidget(self.back_btn, 3, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Passcode)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 65))
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.enter_btn = QtWidgets.QPushButton(Passcode)
        self.enter_btn.setMinimumSize(QtCore.QSize(0, 65))
        self.enter_btn.setStyleSheet("QPushButton{\n"
                                     "border: 1px outset;\n"
                                     "border-color: rgb(98, 98, 91);\n"
                                     "background-color: rgb(39, 68, 114);\n"
                                     "    color: rgb(212, 211, 197);\n"
                                     "\n"
                                     "font:20pt \"Arial\";\n"
                                     "\n"
                                     "\n"
                                     "\n"
                                     "\n"
                                     "}\n"
                                     "\n"
                                     "\n"
                                     "\n"
                                     "QPushButton:pressed{ \n"
                                     "    \n"
                                     "    background-color: rgb(24, 43, 71);\n"
                                     "\n"
                                     "}")
        self.enter_btn.setObjectName("enter_btn")
        self.gridLayout.addWidget(self.enter_btn, 3, 2, 1, 1)
        self.pushButton_1 = QtWidgets.QPushButton(Passcode)
        self.pushButton_1.setMinimumSize(QtCore.QSize(0, 65))
        self.pushButton_1.setStyleSheet("")
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout.addWidget(self.pushButton_1, 0, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(Passcode)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 65))
        self.pushButton_4.setStyleSheet("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(4, 2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.retranslateUi(Passcode)
        QtCore.QMetaObject.connectSlotsByName(Passcode)

    def retranslateUi(self, Passcode):
        _translate = QtCore.QCoreApplication.translate
        Passcode.setWindowTitle(_translate("Passcode", "Passcode"))
        self.go_back_btn.setText(_translate( "Passcode", "<<<BACK"))
        self.title_lbl.setText(_translate("Passcode", "ENTER PASSCODE"))
        self.passcode_lbl.setText(_translate("Passcode", "XXXX"))
        self.pushButton_3.setText(_translate("Passcode", "3"))
        self.pushButton_9.setText(_translate("Passcode", "9"))
        self.pushButton_5.setText(_translate("Passcode", "5"))
        self.pushButton_7.setText(_translate("Passcode", "7"))
        self.pushButton_0.setText(_translate("Passcode", "0"))
        self.pushButton_6.setText(_translate("Passcode", "6"))
        self.pushButton_8.setText(_translate("Passcode", "8"))
        self.pushButton_2.setText(_translate("Passcode", "2"))
        self.enter_btn.setText(_translate("Passcode", "done"))
        self.pushButton_1.setText(_translate("Passcode", "1"))
        self.pushButton_4.setText(_translate("Passcode", "4"))


    def button_clicked(self):
        button = self.sender()
        if button is not None:
                if len(self.passcode) < 4:
                        self.passcode += button.text()
                        self.passcode_lbl.setText("*" * len(self.passcode))
                else:
                        self.notif_lbl.setText("Maximum of 4 digits!")

    def backspace(self):
        self.passcode = self.passcode[:-1]
        self.passcode_lbl.setText("*" * len(self.passcode))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Passcode = QtWidgets.QWidget()
    ui = Ui_Passcode()
    ui.setupUi(Passcode)
    Passcode.show()
    sys.exit(app.exec_())
