# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDesktopWidget
from img import settings_icons_rc

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(310, 190)
        Settings.setMinimumSize(QtCore.QSize(310, 190))
        Settings.setMaximumSize(QtCore.QSize(310, 190))
        Settings.setAutoFillBackground(False)
        Settings.setStyleSheet("background-color: rgb(39, 68, 114);")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Settings)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.VLayout1 = QtWidgets.QVBoxLayout()
        self.VLayout1.setObjectName("VLayout1")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.VLayout1.addItem(spacerItem)
        self.setBTN = QtWidgets.QPushButton(Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setBTN.sizePolicy().hasHeightForWidth())
        self.setBTN.setSizePolicy(sizePolicy)
        self.setBTN.setMinimumSize(QtCore.QSize(0, 30))
        self.setBTN.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.setBTN.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"background-color:rgb(225, 224, 209);\n"
"border-radius: 15px;\n"
"font: 10pt \"Arial\"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:pressed{ \n"
"    \n"
"    background-color: rgb(38, 41, 45);\n"
"    color: rgb(255, 255, 255)}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/lock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setBTN.setIcon(icon)
        self.setBTN.setIconSize(QtCore.QSize(22, 22))
        self.setBTN.setObjectName("setBTN")
        self.VLayout1.addWidget(self.setBTN)
        self.devBTN = QtWidgets.QPushButton(Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.devBTN.sizePolicy().hasHeightForWidth())
        self.devBTN.setSizePolicy(sizePolicy)
        self.devBTN.setMinimumSize(QtCore.QSize(0, 30))
        self.devBTN.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.devBTN.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"background-color:rgb(225, 224, 209);\n"
"border-radius: 15px;\n"
"font: 10pt \"Arial\"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:pressed{ \n"
"    \n"
"    background-color: rgb(223, 195, 53);\n"
"    color: rgb(255, 255, 255)}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/dev.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.devBTN.setIcon(icon1)
        self.devBTN.setObjectName("devBTN")
        self.VLayout1.addWidget(self.devBTN)
        self.VLayout1.setStretch(1, 1)
        self.VLayout1.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.VLayout1)
        self.line = QtWidgets.QFrame(Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setStyleSheet("color: rgb(225, 224, 209);")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(1)
        self.line.setMidLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.VLayout2 = QtWidgets.QVBoxLayout()
        self.VLayout2.setObjectName("VLayout2")
        self.shutBTN = QtWidgets.QPushButton(Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shutBTN.sizePolicy().hasHeightForWidth())
        self.shutBTN.setSizePolicy(sizePolicy)
        self.shutBTN.setMinimumSize(QtCore.QSize(0, 30))
        self.shutBTN.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.shutBTN.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"background-color:rgb(225, 224, 209);\n"
"border-radius: 15px;\n"
"font: 10pt \"Arial\"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:pressed{ \n"
"    \n"
"    background-color:rgb(153, 37, 37);\n"
"    color: rgb(255, 255, 255)}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/shutdown.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shutBTN.setIcon(icon2)
        self.shutBTN.setFlat(True)
        self.shutBTN.setObjectName("shutBTN")
        self.VLayout2.addWidget(self.shutBTN)
        self.rebootBTN = QtWidgets.QPushButton(Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rebootBTN.sizePolicy().hasHeightForWidth())
        self.rebootBTN.setSizePolicy(sizePolicy)
        self.rebootBTN.setMinimumSize(QtCore.QSize(0, 30))
        self.rebootBTN.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rebootBTN.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"background-color:rgb(225, 224, 209);\n"
"border-radius: 15px;\n"
"font: 10pt \"Arial\"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:pressed{ \n"
"    background-color: rgb(29, 200, 69);\n"
"    color: rgb(255, 255, 255)}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/reboot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rebootBTN.setIcon(icon3)
        self.rebootBTN.setObjectName("rebootBTN")
        self.VLayout2.addWidget(self.rebootBTN)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.VLayout2.addItem(spacerItem1)
        self.VLayout2.setStretch(0, 1)
        self.VLayout2.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.VLayout2)
        
        # Center the widget on the screen
        screen_geometry = QDesktopWidget().screenGeometry()
        x = (screen_geometry.width() - self.width()) / 2
        y = (screen_geometry.height() - self.height()) / 2
        self.move(x, y)

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Settings"))
        self.setBTN.setText(_translate("Settings", "Set Password"))
        self.devBTN.setText(_translate("Settings", "   DevMode"))
        self.shutBTN.setText(_translate("Settings", "   Shutdown"))
        self.rebootBTN.setText(_translate("Settings", "   Reboot"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Settings = QtWidgets.QWidget()
    ui = Ui_Settings()
    ui.setupUi(Settings)
    Settings.show()
    sys.exit(app.exec_())
